### PR TITLE
3.x Migration

### PR DESCRIPTION
**Pull request by YakovlevCoded**
Hi! Have a good day

### CODE REVIEW

**Comment by YakovlevCoded** [comment]
@igorlukanin

**Comment by jerairrest** [comment]
Hey! I appreciate the work. :) Can you please use the branch `react16` as a source branch instead of `master`? That's currently what's deployed to https://www.npmjs.com/package/@reactchartjs/react-chart.js which will be the "new" version

**Comment by lobaak** [comment]
@jerairrest is there a chance we can get this through?

**Comment by YakovlevCoded** [comment]
> @jerairrest is there a chance we can get this through?

Hello! We continued to work on this. in the near future, it will definitely be released.

**Pull request closed without merging**
