### PR TITLE
Update ChartJS to 3.5.1 and fix dataset tracking.

### PR DESCRIPTION
**Pull request by basicer**

### CODE REVIEW

**Comment by basicer** [comment]
Hey @YakovlevCoded , did you get a chance to look at this?  The big draw is that it fixes chart animation when you update the datasources.

It's blocking open-sourcing a project I've been working on, as it's package.json file is stuck referring to a local, patched version of react-chartjs-2.

**Comment by lobaak** [comment]
Hey @YakovlevCoded. We're also keen to get this one when you have time 👍

**Comment by anemoiusjerry** [comment]
Hello just a bump on this, as the animation fix would be lovely thanks

**Comment by anemoiusjerry** [comment]
Is there anyway to install this branch directly? Seeing it has been 19 days and no review. I tried using npm i "github link" but the module folder only has readme.md and license files

**Comment by basicer** [comment]
Not really, because of typescript its tricky.  If this lingers for too much longer I'll make a hard fork and push to NPM.

**Comment by YakovlevCoded** [comment]
Hi! Merged and published by 3.0.5 version to [npm](https://www.npmjs.com/package/react-chartjs-2/v/3.0.5). Thank you very much! @basicer

**Pull request merged**
